# Site settings
title: gradient descent
header-img: img/home-bg.jpg
email: ymjung.joshua@gmail.com
copyright_name: Josh Yongmin Jung
description: "Tech/Investment/Datascience"
baseurl: ""
url: "http://h3imdallr.github.io"
twitter_username:
github_username:  h3imdallr
facebook_username: josh.jung.1986
email_username:

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
